name: chess960
version: 1.0.0
description: Chess960.dart is a fork of the chess.dart package. It is a library for legal chess960 move generation, maintenance of game state, and conversion to and from the FEN and PGN formats.
homepage: https://github.com/alexobviously/chess960.dart
dev_dependencies:
  benchmark_harness: ^2.0.0
  test: ^1.17.8
  pedantic: ^1.11.0
environment:
  sdk: '>=2.12.0-0 <3.0.0'

